// My abstract class ids:

#define OTHER_CLASS_ID_INVALID					0xFFFFFFFF
#define OTHER_CLASS_ID_TALK_PACKS				0x01FFFFFF
#define OTHER_CLASS_ID_ANIM_PARAMS				0x02FFFFFF
#define OTHER_CLASS_ID_SOUND_PACK				0x03FFFFFF
#define OTHER_CLASS_ID_PASSIVE_ANIM_PARAMS		0x04FFFFFF
#define OTHER_CLASS_ID_TALK_PACK_DELAYS			0x05FFFFFF
#define OTHER_CLASS_ID_PLAYER_TALK_PACK			0x06FFFFFF
#define OTHER_CLASS_ID_PLAYER_TALK_PACK_DELAYS	0x07FFFFFF
#define OTHER_CLASS_ID_MUSIC_PACK				0x08FFFFFF
#define OTHER_CLASS_ID_EXPERIENCE_PARAMS		0x09FFFFFF
#define OTHER_CLASS_ID_MESH_BUTTON_VIEW_PARAMS	0x0AFFFFFF
#define OTHER_CLASS_ID_SELECTION_MESHES			0x0BFFFFFF
#define OTHER_CLASS_ID_SPECIAL_UPDATES_LINKS	0x0CFFFFFF
#define OTHER_CLASS_ID_RACE_DATA				0x0DFFFFFF
#define OTHER_CLASS_ID_RPG_PARAMS				0x0EFFFFFF
#define OTHER_CLASS_ID_RPG_EXPERIENCE			0x0FFFFFFF